### ISSUE TITLE
figures in readme

### ISSUE THREAD

**Issue by lucasccrema** [SargisYonan/uKal#2]
Hi.
I cannot see the figures in readme file.
Luca

**Comment by SargisYonan** [comment]
Hi Luca,
I've fixed the rendering of the TeX in the latest commit to master.

Here's the raw TeX in case you still can't see the rendering in the markdown
```
If you have model that looks like this:
\vec{x}_{k+1} = \Phi_k \vec{x}_{k} + \Gamma_k \vec{w}_k

or this:
\vec{f}(\vec{x}_{k}, \vec{w}_k)

And you have a measurement model that looks like this:
\vec{y}_k = H_k \vec{x}_k + \vec{\nu}_k

or this:

\vec{y}_k = \vec{h}_k(\vec{x}_k) + \vec{\nu}_k

P, Q, R
```

--Sargis

**Comment by lucasccrema** [comment]
Thank you!
Luca.

2020-05-04 20:41 GMT+02:00, Sargis Yonan <notifications@github.com>:
> Hi Luca,
> I've fixed the rendering of the TeX in the latest commit to master.
>
> Here's the raw TeX in case you still can't see the rendering in the
> markdown
> ```
> If you have model that looks like this:
> \vec{x}_{k+1} = \Phi_k \vec{x}_{k} + \Gamma_k \vec{w}_k
>
> or this:
> \vec{f}(\vec{x}_{k}, \vec{w}_k)
>
> And you have a measurement model that looks like this:
> \vec{y}_k = H_k \vec{x}_k + \vec{\nu}_k
>
> or this:
>
> \vec{y}_k = \vec{h}_k(\vec{x}_k) + \vec{\nu}_k
>
> P, Q, R
> ```
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/SargisYonan/uKal/issues/2#issuecomment-623635874


-- 
Luca S.
